### ISSUE TITLE
localtunnel server returned an error...

### ISSUE THREAD

**Issue by jShi-git** [localtunnel/server#40] opened 2015-12-16 08:55 UTC
```
/usr/local/lib/node_modules/localtunnel/bin/client:48
        throw err;
        ^

Error: localtunnel server returned an error, please try again
    at Request._callback (/usr/local/lib/node_modules/localtunnel/lib/Tunnel.js:53:27)
    at Request.self.callback (/usr/local/lib/node_modules/localtunnel/node_modules/request/request.js:198:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/localtunnel/node_modules/request/request.js:1082:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/localtunnel/node_modules/request/request.js:1009:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
```

**Comment by smoothdvd** [comment] 2015-12-27 04:06
same error

**Comment by tomneedham** [comment] 2016-10-18 15:15
I get this as well, any suggestions?

**Comment by tomneedham** [comment] 2016-10-18 15:18
Seems like this is the issue https://github.com/localtunnel/server/issues/31 and this is a proposed solution: https://github.com/localtunnel/server/pull/50

**Comment by wenhongquan** [comment] 2016-12-12 07:20
same

**Comment by AnushaPendyam** [comment] 2017-03-09 07:17
C:\angular\intro-to-webdev-app-master\intro-to-webdev-app-master\app>lt --port 8080 

C:\Users\anushap\AppData\Roaming\npm\node_modules\localtunnel\bin\client:48
        throw err;
        ^

Error: localtunnel server returned an error, please try again
    \AppData\Roaming\npm\node_modules\loca
ltunnel\lib\Tunnel.js:53:27)
    at Request.self.callback (C:\Users\anushap\AppData\Roaming\npm\node_modules\
localtunnel\node_modules\request\request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\Users\anushap\AppData\Roaming\npm\node_modules\lo
caltunnel\node_modules\request\request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (C:\Users\anushap\AppData\Roaming\npm\node_mo
dules\localtunnel\node_modules\request\request.js:1001:12)
    at IncomingMessage.g (events.js:286:16)
    at emitNone (events.js:91:20)

**Comment by buoyantair** [comment] 2017-04-17 08:48
I get the same error too D:

**Comment by AnushaPendyam** [comment] 2017-04-18 11:54
It's due to SSL certification error in the system

**Comment by buoyantair** [comment] 2017-04-18 13:40
@AnushaPendyam How to fix it?

**Comment by AnushaPendyam** [comment] 2017-04-18 17:42
Check if there are any security privileges for the system and try to update SSL certificate.Due to security privileges  I'm not suppose to update SSL certificates in the office PC so I did not fix it in the same system. when I did it in my Personal PC it's working fine without any errors
![untitled](https://cloud.githubusercontent.com/assets/24385477/25144707/70d3dee8-248c-11e7-8434-39b3092b9394.png)
.

**Comment by tlynch001** [comment] 2017-05-15 12:15
I don't understand "Check if there are any security privileges for the system and try to update SSL certificate".  Could someone explain it?  Due to SSL error in "system"?  What system?

**Comment by dingjb** [comment] 2017-09-15 02:23
I got the same error too,

At first i clone the repository into my local, when i run `npm install`, i get an error about `node-gyp build` or `utf-8-validate`, i find this was gcc version wrong, so i update gcc version,
```sh
# gcc 5.2
yum install centos-release-scl
yum install devtoolset-4-toolchain
scl enable devtoolset-4 bash
gcc --version
```
then i run command `npm install ` correctly has no error。

And next, i found is also has this error `localtunnel server returned an error`,
then i found it was my nginx config error，you can checkout to branch `error-handle` 
and then will find a directory called `devops`, then you get nginx config and host config,
in my case , i was config error `location` node, 

![image](https://user-images.githubusercontent.com/14836552/30463617-5a122f5a-99ff-11e7-8e37-b39d61aa6d51.png)

ok , you will get your own url, everything ok ?

when i connected my localtunnel server , i found it's auto close after a few seconds in my server command line output。
if you find this error, you should check you iptables, 
when i run `service iptables stop`, it's work fine~~

Good luck!!!

**Comment by ForsakenHarmony** [comment] 2017-10-09 04:50
I'm using docker with traefik, same error

**Comment by mababio** [comment] 2017-11-13 18:07
This is still an issue? I currently debugging. I can see a bad return code was returned. It was a 502 error code.

**Comment by mababio** [comment] 2017-11-13 18:11
Okay, I took a look at other reported issue and it seems the localtunnel.me is down. Not sure if the unreliability  and the reported error message are related

**Comment by ladykate17** [comment] 2017-11-13 18:13
@mababio Having the same issue, issues just starting this morning for me.

**Comment by mababio** [comment] 2017-11-13 18:19
@ladykate17  It's the first time I'm using localtunnel. It worked in the past for you?

**Comment by ladykate17** [comment] 2017-11-13 18:26
@mababio Newer to it as well, but it was working great the last couple weeks I've been using it. I've heard from coworkers it can be unreliable at times. If I find anything I'll try to post back here.

**Comment by mababio** [comment] 2017-11-13 18:43
@ladykate17  Thanks for the for info! Also your website and resume is groovy 
@defunctzombie I didn't get a chance to use your awesome tool, but thanks for all the effort you put into this open source tool.

**Comment by laloumen** [comment] 2017-11-13 19:50
This was working for me on Friday but today is not. So, localtunnel.me is down and there is no workaround or anything?

**Comment by samrod** [comment] 2017-11-13 19:56
Yup same herer. Was working Friday and it's now down for me too folks with the same error.

**Comment by ladykate17** [comment] 2017-11-13 19:57
It's an ongoing issue - https://github.com/localtunnel/localtunnel/issues/123#issuecomment-343933449 I suppose the solution is find another node wrapper to use for the time being.

**Comment by samrod** [comment] 2017-11-13 21:28
Alright, it's back up. I guess localtunnel.me was just down. Are there either fallback or alternative servers available for such cases?

**Comment by damianobarbati** [comment] 2018-02-08 12:03
`Error: localtunnel server returned an error, please try again` @@

**Comment by William-An** [comment] 2018-03-03 03:29
#69 is also about this error. It is probably due to the use of subdomain like `sub.example.com` as host.

**Comment by defunctzombie** [comment] 2018-04-02 01:31
It is unclear to me if there is a specific issue here with localtunnel server or if the issue is a connectivity or general uptime one. I am going to close this since I _think_ the core of this issue is just localtunnel.me uptime but if there is a specific reproducible case with the server logic please open a new issue with steps to reproduce.

**Closed by defunctzombie** 2018-04-02 01:31 UTC

**Comment by ForsakenHarmony** [comment] 2018-04-02 13:05
this happens all of the time with self hosted servers
